# Generated by Django 3.2.25 on 2025-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('transaction_date', models.DateTimeField()),
                ('bookkeeping_date', models.DateTimeField()),
                ('card_id', models.CharField(max_length=64)),
                ('transaction_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_currency', models.CharField(max_length=16)),
                ('balance_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_desc', models.TextField()),
                ('payment_type_id', models.CharField(max_length=32)),
                ('payment_type_name', models.CharField(max_length=64)),
                ('card_type_id', models.IntegerField(default=1)),
                ('card_type_name', models.CharField(default='Credit Card', max_length=64)),
                ('deleted', models.IntegerField(default=0)),
                ('consumption_name', models.CharField(max_length=64)),
                ('consumption_id', models.IntegerField()),
                ('consume_name', models.CharField(max_length=64)),
                ('consume_id', models.CharField(max_length=64)),
                ('keyword', models.CharField(max_length=128)),
                ('demoarea', models.CharField(max_length=128)),
                ('recordid', models.CharField(default='no record id', max_length=64)),
                ('version', models.IntegerField(default=0)),
                ('createuser', models.CharField(default='system', max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updateuser', models.CharField(default='system', max_length=64)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CREDIT',
            },
        ),
    ]
